[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.input]
env = {"CARGO_MAKE_RUST_SCRIPT_PROVIDER" = "cargo-play"}
script = '''
//# aoc-shared = { git = "https://github.com/dwalker109/aoc-shared.git" }

fn main() {
    if std::path::Path::new("./input").exists() {
      println!(r#""./input" already exists, nothing to do"#);
      return;
    }

    let crate_name = std::env::var("CARGO_MAKE_CRATE_NAME").unwrap();
    let token = std::env::var("AOC_TOKEN").unwrap();
    let day = &crate_name[3..].parse::<u8>().unwrap();

    let data = aoc_shared::input::download(&token, &2016, &day).unwrap();
    aoc_shared::input::save("./input", &data).unwrap();

    println!(r#"Saved {} bytes to "./input""#, data.len());
}
'''
script_runner = "@rust"
